```{r}
#### Workspace setup ####
library(tidyverse)
library(GGally)
data <- read_csv(here::here("data/data.csv"))
```

```{r}
library(stringr)
data$price_numeric <- as.numeric(str_replace_all(data$price, "\\$|/100g", ""))
```

```{r}

voila_data <- subset(data, vendor == "Voila")


plot_voila <- ggplot(voila_data, aes(x = price_numeric)) +
  geom_histogram(binwidth = 0.1, fill = "blue", color = "black", alpha = 0.7) +
  labs(title = "Voila",
       x = "price/100g",
       y = "frequence") +
  theme_minimal()


print(plot_voila)
```

```{r}


Metro_data <- subset(data, vendor == "Metro")


plot_Metro <- ggplot(Metro_data, aes(x = price_numeric)) +
  geom_histogram(binwidth = 0.1, fill = "blue", color = "black", alpha = 0.7) +
  labs(title = "Metro",
       x = "price/100g",
       y = "frequence") +
  theme_minimal()


print(plot_Metro)
```

```{r}


NoFrills_data <- subset(data, vendor == "NoFrills")


plot_NoFrills <- ggplot(NoFrills_data, aes(x = price_numeric)) +
  geom_histogram(binwidth = 0.1, fill = "blue", color = "black", alpha = 0.7) +
  labs(title = "NoFrills",
       x = "price/100g",
       y = "frequence") +
  theme_minimal()


print(plot_NoFrills)
```
```{r}
c1 <- voila_data$price_numeric
c2 <- Metro_data$price_numeric
c3 <- NoFrills_data$price_numeric

min_length <- min(length(c1), length(c2), length(c3))
voila_price <- c1[1:min_length]
metro_price <- c2[1:min_length]
nofrills_price <- c3[1:min_length]
data2 <- data.frame(voila_price, metro_price, nofrills_price)
pairs(data2)
```

